### PR TITLE
Fixup/delint

### PR DESCRIPTION
**Pull request by egeland**
A bunch of delintings, to try to make rubocop happier.

Note that I have **not** tested the app, either before or after these changes, so I suggest you do!

### CODE REVIEW

**Comment by jethrocarr** [comment]
Thanks Frode, will review, merge and test.

If you are able to add information on how to style check with Rubocop to the README.md (down near the bottom under "Developing") it would be a big plus to help other newbie developers to the project to keep things clean.

**Comment by egeland** [comment]
I intend to go one better than just updating doco.. ;-)

I'll spill the beans: I want to put a decent Rakefile in this project, with tests and rubocop-ing :)

**Comment by jethrocarr** [comment]
Nice - I'd like to write some test suites using the pupistry-samplepuppet repo I have and something like AWS or DigitalOcean API to do end-to-end testing of building and pushing an artifact and then applying on a machine and checking the outputs from a Puppet run. 

You'll notice that the pupistry-samplepuppet output already some some basic tests like making sure hiera lookups are working etc, so easy to build from that.

**Comment by egeland** [comment]
Let's use [Travis CI](https://travis-ci.org/) for running the tests, since this thing is Free Software.. ?

**Comment by jethrocarr** [comment]
Sounds good, let's give it a go. I've added it to Travis CI, just need to get the config file... and tests added ;-)

**Comment by egeland** [comment]
I've added a basic travis config file, see #6 :)

**Pull request merged**
