### PR TITLE
Feature/basic tests

### PR DESCRIPTION
**Pull request by egeland**
Adding some tests, there are some that are red :scream_cat: , i.e the code needs to be changed to make them green (if you agree with their premises).

### CODE REVIEW

**Comment by egeland** [comment]
Oh, and I shuffled files around a bit, so test to make sure stuff still works!

**Comment by jethrocarr** [comment]
Agree with the premise :-)

I see you've mentioned a file settingspec.example.yaml but it's not in the PR - missing git add?

**Comment by egeland** [comment]
Fixed that "missing file" - it was a search/replace error..

**Comment by egeland** [comment]
So it's been tested, then?

**Comment by jethrocarr** [comment]
I wouldn't go that far... but I need to merge it before I can properly test it.

**Comment by jethrocarr** [comment]
OK have made some fixes including app changes to handle various invalid config files better and have committed along with this merge into master.

**Comment by egeland** [comment]
Cool :)

**Comment by egeland** [comment]
Oh, in regards to 'need to merge before testing can be done', should this project start using the 'git flow' branching more officially?
I.e. `master` is always the clean, production ready code, `develop` is where you merge in new stuff and `feature/<foo>` (usually in a forked repo) is how you do new features.
If you think this is a good plan, just make a `develop` branch and I'll target future PRs to it, rather than `master`.

**Pull request merged**
